language: node_js
node_js:
  - 12.18.4

cache:
  directories:
  - node_modules

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages