language: node_js
node_js:
  - 12.18.4
cache:
  directories:
  - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main  